# Generated by Django 6.0.1 on 2026-01-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPetani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('alamat', models.TextField()),
                ('whatsapp', models.CharField(max_length=20)),
                ('komoditas', models.CharField(max_length=100)),
                ('riwayat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_petani', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('tanaman', models.CharField(max_length=100)),
                ('luas', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('stok', models.CharField(max_length=50)),
                ('harga', models.CharField(blank=True, max_length=50)),
                ('foto', models.ImageField(upload_to='produk/')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilPetani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('foto', models.ImageField(upload_to='profil/')),
            ],
        ),
    ]
