# Generated by Django 6.0.1 on 2026-01-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produk',
            old_name='nama',
            new_name='nama_produk',
        ),
        migrations.AlterField(
            model_name='produk',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='produk/'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='harga',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='produk',
            name='stok',
            field=models.CharField(default='Masih proses tanam', max_length=50),
        ),
    ]
