# Generated by Django 6.0.1 on 2026-01-15 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_nama_produk_nama_produk_alter_produk_foto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailpetani',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='lahan',
            name='nama_petani',
        ),
        migrations.AddField(
            model_name='detailpetani',
            name='profil',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='main.profilpetani'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lahan',
            name='petani',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lahan', to='main.profilpetani'),
        ),
        migrations.AddField(
            model_name='produk',
            name='petani',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produk', to='main.profilpetani'),
        ),
        migrations.AlterField(
            model_name='profilpetani',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profil/'),
        ),
        migrations.CreateModel(
            name='HasilPanen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_panen', models.CharField(max_length=100)),
                ('jumlah', models.FloatField(help_text='Dalam Kg')),
                ('tanggal_panen', models.DateField()),
                ('keterangan', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='hasil_panen/')),
                ('petani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_panen', to='main.profilpetani')),
            ],
        ),
        migrations.AddField(
            model_name='produk',
            name='hasil_panen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.hasilpanen'),
        ),
    ]
